<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Configuration</title>
<link rel="stylesheet" type="text/css" href="CSS/common1.css">
<link rel="stylesheet" type="text/css" href="CSS/style.css">
<style type="text/css">
     body, html, form { height:95.5%; }
     .Inner
     {
        height:400px;
     }      
    </style>
</head>
<body style="margin: 0;" bgcolor="white" onload="FormLoad();"> 
<form method="post" action="Configuration_Config.aspx" onsubmit="javascript:return window.WebForm_OnSubmit();" onkeypress="javascript:return window.WebForm_FireDefaultButton(event, 'ctl00_DoNothing')" id="ctl00_form1" >
<script type="text/javascript">//<![CDATA[
	var theForm;
	if (document.getElementById) { theForm = document.getElementById ('ctl00_form1'); }
	else { theForm = document.ctl00_form1; }
//]]></script>

<div class="aspNetHidden">


<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEMDAwQAgAADgEMBQAMEAIAAA4BDAUDDBACAAAOEAwFAgwQAgwADwEBBXN0eWxlAT90ZXh0LXRyYW5zZm9ybTogY2FwaXRhbGl6ZTsgdGV4dC1hbGlnbjogbGVmdDsgcGFkZGluZy10b3A6IDVweDsAAAwFBAwQAgwPAQEEVGV4dAEGTUhDMDM5DwECAAABLXRleHQtdHJhbnNmb3JtOiBjYXBpdGFsaXplOyB0ZXh0LWFsaWduOiBsZWZ0OwAADAUFDBACDA8BAgIAAR5NYWhlbmRyYSBTaGFybWEgQ29tcGFueSAoQ09ETykPAQIAAAIEAAAADAUGDBACDA8BAgIAARVTdGF0aW9uIENvZGUgOiAyNjg1MzIPAQIAAAESdGV4dC1hbGlnbjogbGVmdDsgAAAMBQcMEAIMDwECAgABHVZlcnNpb24gOiAyLjAuNCAoMjUtRmViLTIwMTUpDwECAAACBwAAAAwFCAwQAgwPAQICAAERV2VsY29tZSBUbyBhZG1pbiAPAQIAAAEudGV4dC10cmFuc2Zvcm06IGNhcGl0YWxpemU7IHRleHQtYWxpZ246IGxlZnQ7IAAADAUJDBACDA8BAgIAAQdSZWZyZXNoDwECAAABEHRleHQtYWxpZ246IGxlZnQAAAwFCgwQAgwPAQICAAEHTG9nb3V0IA8BAgAAAgwAAAAMBQsMEAIMDwECAgABC0xJVkUgQUxBUk1TDwECAAABZmZvbnQtd2VpZ2h0OiBib2xkOyB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlOyBmb250LWZhbWlseTogQXJpYWw7IGZvbnQtc2l6ZTogMTNweDsgdGV4dC1hbGlnbjogY2VudGVyOwAADAVMDBACDAAPAQEBcwAAAAwFUAwQAgAADgEMBQAMEAIAAA4BDAUBDBACEAkMDwMBCl9EYXRhQm91bmQIAQVJdGVtcwUKAQhEYXRhS2V5cw4AAAAAAAAAAAAAAA4KDAUADBACAAAOCAwFAwwQAgwPAwEJRm9yZUNvbG9yGI0AAAACAgABEzIyLzA0LzIwMTUgMTI6MTc6NDABBF8hU0IFBA8BAgAAARF0ZXh0LWFsaWduOiBsZWZ0OwAADAUFDBACDA8BAgIAAQEwDwECAAACFwAAAAwFBwwQAgwPAwIUABiNAAAAAgIAAQQ0MTc4AhYABQQPAQIAAAIXAAAADAUJDBACDA8CAhQAGI0AAAACFgAFBAAAAAwFCgwQAgwPAwIUABiNAAAAAgIAAQdQcmludGVyAhYABQQPAQIAAAIXAAAADAUMDBACDA8CAhQAGI0AAAACFgAFBA8BAgAAAhcAAAAMBQ0MEAIMDwMCFAAYjQAAAAICAAEESGlnaAIWAAUEDwECAAACBwAAAAwFDwwQAgwPAwIUABiNAAAAAgIAAR9QUklOVEVSOjIgQ29tbXVuaWNhdGlvbiBPZmZsaW5lAhYABQQPAQIAAAEjdGV4dC1hbGlnbjogbGVmdDsgcGFkZGluZy10b3A6NXB4OyAAAAwFAQwQAgAADggMBQMMEAIMDwMCFAAYjQAAAAICAAETMjIvMDQvMjAxNSAxMjoxNjowNgIWAAUEDwECAAACFwAAAAwFBQwQAgwPAQICAAIYAA8BAgAAAhcAAAAMBQcMEAIMDwMCFAAYjQAAAAICAAEENDE3NgIWAAUEDwECAAACFwAAAAwFCQwQAgwPAgIUABiNAAAAAhYABQQAAAAMBQoMEAIMDwMCFAAYjQAAAAICAAIaAAIWAAUEDwECAAACFwAAAAwFDAwQAgwPAgIUABiNAAAAAhYABQQPAQIAAAIXAAAADAUNDBACDA8DAhQAGI0AAAACAgACGwACFgAFBA8BAgAAAgcAAAAMBQ8MEAIMDwMCFAAYjQAAAAICAAIcAAIWAAUEDwECAAACHQAAAAwFAgwQAgAADggMBQMMEAIMDwMCFAAYjQAAAAICAAETMjIvMDQvMjAxNSAxMDoyNDozMwIWAAUEDwECAAACFwAAAAwFBQwQAgwPAQICAAIYAA8BAgAAAhcAAAAMBQcMEAIMDwMCFAAYjQAAAAICAAEENDE2NAIWAAUEDwECAAACFwAAAAwFCQwQAgwPAgIUABiNAAAAAhYABQQAAAAMBQoMEAIMDwMCFAAYjQAAAAICAAIaAAIWAAUEDwECAAACFwAAAAwFDAwQAgwPAgIUABiNAAAAAhYABQQPAQIAAAIXAAAADAUNDBACDA8DAhQAGI0AAAACAgACGwACFgAFBA8BAgAAAgcAAAAMBQ8MEAIMDwMCFAAYjQAAAAICAAIcAAIWAAUEDwECAAACHQAAAAwFAwwQAgAADggMBQMMEAIMDwMCFAAYjQAAAAICAAETMjIvMDQvMjAxNSAwNzozNTowNAIWAAUEDwECAAACFwAAAAwFBQwQAgwPAQICAAIYAA8BAgAAAhcAAAAMBQcMEAIMDwMCFAAYjQAAAAICAAEENDEyOQIWAAUEDwECAAACFwAAAAwFCQwQAgwPAgIUABiNAAAAAhYABQQAAAAMBQoMEAIMDwMCFAAYjQAAAAICAAIaAAIWAAUEDwECAAACFwAAAAwFDAwQAgwPAgIUABiNAAAAAhYABQQPAQIAAAIXAAAADAUNDBACDA8DAhQAGI0AAAACAgACGwACFgAFBA8BAgAAAgcAAAAMBQ8MEAIMDwMCFAAYjQAAAAICAAIcAAIWAAUEDwECAAACHQAAAAwFBAwQAgAADggMBQMMEAIMDwMCFAAYjQAAAAICAAETMjIvMDQvMjAxNSAwNjo1ODozNQIWAAUEDwECAAACFwAAAAwFBQwQAgwPAQICAAIYAA8BAgAAAhcAAAAMBQcMEAIMDwMCFAAYjQAAAAICAAEENDEyNQIWAAUEDwECAAACFwAAAAwFCQwQAgwPAgIUABiNAAAAAhYABQQAAAAMBQoMEAIMDwMCFAAYjQAAAAICAAIaAAIWAAUEDwECAAACFwAAAAwFDAwQAgwPAgIUABiNAAAAAhYABQQPAQIAAAIXAAAADAUNDBACDA8DAhQAGI0AAAACAgACGwACFgAFBA8BAgAAAgcAAAAMBQ8MEAIMDwMCFAAYjQAAAAICAAIcAAIWAAUEDwECAAACHQAAAAwFBQwQAgAADggMBQMMEAIMDwMCFAAYjQAAAAICAAETMjIvMDQvMjAxNSAwNjoxNTo0MQIWAAUEDwECAAACFwAAAAwFBQwQAgwPAQICAAIYAA8BAgAAAhcAAAAMBQcMEAIMDwMCFAAYjQAAAAICAAEENDExNAIWAAUEDwECAAACFwAAAAwFCQwQAgwPAgIUABiNAAAAAhYABQQAAAAMBQoMEAIMDwMCFAAYjQAAAAICAAIaAAIWAAUEDwECAAACFwAAAAwFDAwQAgwPAgIUABiNAAAAAhYABQQPAQIAAAIXAAAADAUNDBACDA8DAhQAGI0AAAACAgACGwACFgAFBA8BAgAAAgcAAAAMBQ8MEAIMDwMCFAAYjQAAAAICAAIcAAIWAAUEDwECAAACHQAAAAwFBgwQAgAADggMBQMMEAIMDwMCFAAYjQAAAAICAAETMjIvMDQvMjAxNSAwNTozODozMQIWAAUEDwECAAACFwAAAAwFBQwQAgwPAQICAAIYAA8BAgAAAhcAAAAMBQcMEAIMDwMCFAAYjQAAAAICAAEENDExMwIWAAUEDwECAAACFwAAAAwFCQwQAgwPAgIUABiNAAAAAhYABQQAAAAMBQoMEAIMDwMCFAAYjQAAAAICAAIaAAIWAAUEDwECAAACFwAAAAwFDAwQAgwPAgIUABiNAAAAAhYABQQPAQIAAAIXAAAADAUNDBACDA8DAhQAGI0AAAACAgACGwACFgAFBA8BAgAAAgcAAAAMBQ8MEAIMDwMCFAAYjQAAAAICAAIcAAIWAAUEDwECAAACHQAAAAwFBwwQAgAADggMBQMMEAIMDwMCFAAYjQAAAAICAAETMjIvMDQvMjAxNSAwNTozNjozMAIWAAUEDwECAAACFwAAAAwFBQwQAgwPAQICAAIYAA8BAgAAAhcAAAAMBQcMEAIMDwMCFAAYjQAAAAICAAEENDExMgIWAAUEDwECAAACFwAAAAwFCQwQAgwPAgIUABiNAAAAAhYABQQAAAAMBQoMEAIMDwMCFAAYjQAAAAICAAIaAAIWAAUEDwECAAACFwAAAAwFDAwQAgwPAgIUABiNAAAAAhYABQQPAQIAAAIXAAAADAUNDBACDA8DAhQAGI0AAAACAgACGwACFgAFBA8BAgAAAgcAAAAMBQ8MEAIMDwMCFAAYjQAAAAICAAIcAAIWAAUEDwECAAACHQAAAAwFCAwQAgAADggMBQMMEAIMDwMCFAAYjQAAAAICAAETMjIvMDQvMjAxNSAwOToxODo1NAIWAAUEDwECAAACFwAAAAwFBQwQAgwPAQICAAIYAA8BAgAAAhcAAAAMBQcMEAIMDwMCFAAYjQAAAAICAAEENDE1MgIWAAUEDwECAAACFwAAAAwFCQwQAgwPAgIUABiNAAAAAhYABQQAAAAMBQoMEAIMDwMCFAAYjQAAAAICAAEEUHVtcAIWAAUEDwECAAACFwAAAAwFDAwQAgwPAgIUABiNAAAAAhYABQQPAQIAAAIXAAAADAUNDBACDA8DAhQAGI0AAAACAgABBk5vcm1hbAIWAAUEDwECAAACBwAAAAwFDwwQAgwPAwIUABiNAAAAAgIAATNSZW1vdGUgUHJlc2V0IFZvbHVtZSBNaXNtYXRjaCBGb3IgVHJhbnNhY3Rpb246MzkzNjYCFgAFBA8BAgAAAh0AAAAMBQkMEAIAAA4IDAUDDBACDA8DAhQAGI0AAAACAgABEzIyLzA0LzIwMTUgMDg6MTQ6MTcCFgAFBA8BAgAAAhcAAAAMBQUMEAIMDwECAgACGAAPAQIAAAIXAAAADAUHDBACDA8DAhQAGI0AAAACAgABBDQxNDICFgAFBA8BAgAAAhcAAAAMBQkMEAIMDwICFAAYjQAAAAIWAAUEAAAADAUKDBACDA8DAhQAGI0AAAACAgACLgACFgAFBA8BAgAAAhcAAAAMBQwMEAIMDwICFAAYjQAAAAIWAAUEDwECAAACFwAAAAwFDQwQAgwPAwIUABiNAAAAAgIAAi8AAhYABQQPAQIAAAIHAAAADAUPDBACDA8DAhQAGI0AAAACAgABM1JlbW90ZSBQcmVzZXQgVm9sdW1lIE1pc21hdGNoIEZvciBUcmFuc2FjdGlvbjozOTIxNAIWAAUEDwECAAACHQAAAAwFUQwQAgAADggMBQMMEAIMDwECAgABHk5vdGUgOiAqIEZpZWxkcyBBcmUgTWFuZGF0b3J5LgAAAAwFBQwQAgwPAwICAAEHR0VORVJBTAEIQ3NzQ2xhc3MBD1ZpZXdTdHlsZUFjdGl2ZQIWAAUCAAAADAUHDBACDA8DAgIAAQdQUk9EVUNUAjYAAQlWaWV3U3R5bGUCFgAFAgAAAAwFCQwQAgwPAwICAAEEVEFOSwI2AAI5AAIWAAUCAAAADAULDBACDA8DAgIAAQlESVNQRU5TRVICNgACOQACFgAFAgAAAAwFDQwQAgwPAwICAAEHUFJJTlRFUgI2AAI5AAIWAAUCAAAADAUPDBACDA8DAgIAAQNVUFMCNgACOQACFgAFAgAAAAwFEwwQAgAADgcMBQAMEAIPAQEHVmlzaWJsZQgADhgMBQMMEAIMDwECAgABCExvY2F0aW9uDwECAAACDAAAAAwFBwwQAgwPAQICAAEFSW5kaWEAAAAMBQ8MEAIMDwECAgABBkphaXB1cgAAAAwFFwwQAgwPAQICAAEJUmFqYXN0aGFuAAAADAUdDBACDA8BAgIAAQdTdGF0aW9uDwECAAACDAAAAAwFIQwQAgwPAQICAAIDAAAAAAwFJwwQAgwPAQICAAEXTWFoZW5kcmEgU2hhcm1hIENvbXBhbnkAAAAMBS8MEAIMDwECAgABBENPRE8AAAAMBTcMEAIMDwECAgABAAAAAAwFPwwQAgwPAQICAAJBAAAAAAwFRwwQAgwPAQICAAESTXIgTWFoZW5kcmEgU2hhcm1hAAAADAVPDBACDA8BAgIAAQ4rOTEtOTQxNDA1MDQzMAAAAAwFVQwQAgwPAQICAAEMU3RhdGlvbiBDb2RlDwECAAACDAAAAAwFWQwQAgwPAQICAAEGMjY4NTMyAAAADAVhDBACDA8BAgIAAQQxMzAxAAAADAVnDBACDA8BAgIAAQ5Db250YWN0IERldGFpbA8BAgAAAgwAAAAMBWsMEAIMDwECAgABDVJJSUNPIFNQNCBFeHQAAAAMBXMMEAIMDwECAgABBkJhZ3J1IAAAAAwFewwQAgwPAQICAAJGAAAAAAwFgwwQAgwPAQICAAJBAAAAAAwFiwwQAgwPAQICAAEGMzAyMDA3AAAADAWTDBACDA8BAgIAAQswMDAtMDAwMDAwMAAAAAwFmwwQAgwPAQICAAELYWJjQHh5ei5jb20AAAAMBacMEAIMDwECAgACRgAAAAAMBQEMEAIAAA4BDAUFDBACAAAOAgwFAAwQAgAADgMMBQcMEAIQEAwPAgEJRGF0YUJvdW5kCAELXyFJdGVtQ291bnQFAgAAAAAAAAAAAAAAAAAAAAAADgEMBQAMEAIAAA4DDAUBDBACAAAOBgwFAQwQAgwPAQICAAEBMQAAAAwFAgwQAgwPAQICAAECTVMAAAAMBQMMEAIMDwECAgABAzEwMQAAAAwFBAwQAgwPAQICAAEERnVlbAAAAAwFBQwQAgwPAQICAAEETHRyLgAAAAwFBgwQAgAADgEMBQEMEAIMDwMCFgAFCAEJQmFja0NvbG9yFwBm//8BB1Rvb2xUaXABByNGRjY2MDAAAAAMBQIMEAIAAA4GDAUBDBACDA8BAgIAAQEyAAAADAUCDBACDA8BAgIAAQNIU0QAAAAMBQMMEAIMDwECAgABAzEwMgAAAAwFBAwQAgwPAQICAAJXAAAAAAwFBQwQAgwPAQICAAJYAAAAAAwFBgwQAgAADgEMBQEMEAIMDwMCFgAFCAJZABglAAAAAloAAQcjMDAwMEZGAAAADAUDDBACDA8BAj4ACQAAAAwFCQwQAgwADwECAAABDWRpc3BsYXk6IG5vbmUADgcMBQMMEAIMAA8BAgAAAQtjdXJzb3I6aGFuZAAADAUFDBACDA8BAgIAAQdQcm9kdWN0DwECAAACDAAAAAwFDwwQAgwAAAAADAURDBACDA8BAgIAAQRDb2RlDwECAAACDAAAAAwFGQwQAgwPAQICAAEHR2VuZXJhbA8BAgAAAgwAAAAMBR0MEAIMAAAAAAwFIQwQAgwAAAAADAULDBACDAAPAQIAAAJgAAAADAUBDBACAAAOAwwFBwwQAhAQDA8CAlIACAJTAAUCAAAAAAAAAAAAAAAAAAAAAAAOAQwFAAwQAgAADgMMBQEMEAIAAA4IDAUBDBACDA8BAgIAAlQAAAAADAUCDBACDA8BAgIAAlUAAAAADAUDDBACDA8BAgIAAlYAAAAADAUEDBACDA8BAgIAAlUAAAAADAUFDBACDA8BAgIAAQMxMDAAAAAMBQYMEAIMDwECAgABBk5vIFNldAAAAAwFBwwQAgwPAQICAAIYAAAAAAwFCAwQAgAADgEMBQEMEAIMDwMCFgAFCAJZABcAZv//AloAAlsAAAAADAUCDBACAAAOCAwFAQwQAgwPAQICAAJcAAAAAAwFAgwQAgwPAQICAAJdAAAAAAwFAwwQAgwPAQICAAJeAAAAAAwFBAwQAgwPAQICAAJdAAAAAAwFBQwQAgwPAQICAAJlAAAAAAwFBgwQAgwPAQICAAJmAAAAAAwFBwwQAgwPAQICAAIYAAAAAAwFCAwQAgAADgEMBQEMEAIMDwMCFgAFCAJZABglAAAAAloAAl8AAAAADAUDDBACDA8BAj4ACQAAAAwFCQwQAgwADwECAAACYAAADgcMBQMMEAIMAA8BAgAAAmEAAAAMBQUMEAIMDwECAgABBUdyYWRlDwECAAACDAAAAAwFEwwQAgwPAQICAAJjAA8BAgAAAgwAAAAMBRsMEAIMDwECAgACZAAPAQIAAAIMAAAADAUfDBACDAAAAAAMBSMMEAIMAAAAAAwFKwwQAgwAAAAADAULDBACDAAPAQIAAAJgAAAADAUCDBACAAAOAQwFBQwQAgAADgIMBQAMEAIAAA4DDAUHDBACEBAMDwICUgAIAlMABQMAAAAAAAAAAAAAAAAAAAAAAA4BDAUADBACAAAOBAwFAQwQAgAADggMBQEMEAIMDwECAgACVAAAAAAMBQIMEAIMDwECAgACXQAAAAAMBQMMEAIMDwECAgABBDIxMDAAAAAMBQQMEAIMDwECAgACVAAAAAAMBQUMEAIMDwECAgABBTIxNjMwAAAADAUGDBACDA8BAgIAAlwAAAAADAUHDBACDA8BAgIAAlQAAAAADAUIDBACAAAOAQwFAQwQAgwPAgJZABglAAAAAhYABQgAAAAMBQIMEAIAAA4IDAUBDBACDA8BAgIAAlwAAAAADAUCDBACDA8BAgIAAl0AAAAADAUDDBACDA8BAgIAAmgAAAAADAUEDBACDA8BAgIAAlQAAAAADAUFDBACDA8BAgIAAmkAAAAADAUGDBACDA8BAgIAAlwAAAAADAUHDBACDA8BAgIAAlQAAAAADAUIDBACAAAOAQwFAQwQAgwPAgJZABglAAAAAhYABQgAAAAMBQMMEAIAAA4IDAUBDBACDA8BAgIAAQEzAAAADAUCDBACDA8BAgIAAlUAAAAADAUDDBACDA8BAgIAAmgAAAAADAUEDBACDA8BAgIAAlQAAAAADAUFDBACDA8BAgIAAmkAAAAADAUGDBACDA8BAgIAAlwAAAAADAUHDBACDA8BAgIAAlQAAAAADAUIDBACAAAOAQwFAQwQAgwPAgJZABcAZv//AhYABQgAAAAMBQQMEAIMDwECPgAJAAAADAUJDBACDAAPAQIAAAJgAAAOBQwFAwwQAgwADwECAAACYQAAAAwFBQwQAgwPAQICAAEEVGFuaw8BAgAAAgwAAAAMBQ8MEAIMAAAAAAwFEQwQAgwPAQICAAELTWVhc3VyZW1lbnQPAQIAAAIMAAAADAUpDBACDA8BAgIAAQtUYW5rIEFsYXJtcw8BAgAAAgwAAAAMBQsMEAIMAA8BAgAAAmAAAAAMBQEMEAIAAA4DDAUHDBACEBAMDwICUgAIAlMABQMAAAAAAAAAAAAAAAAAAAAAAA4BDAUADBACAAAOBAwFAQwQAgAADgUMBQEMEAIMDwECAgACVAAAAAAMBQIMEAIAAA4BDAUBDBACDA8BAgIAAQNPUFcAAAAMBQMMEAIMDwECAgACVAAAAAAMBQQMEAIMDwECAgABATYAAAAMBQUMEAIMDwECAgACVAAAAAAMBQIMEAIAAA4FDAUBDBACDA8BAgIAAlwAAAAADAUCDBACAAAOAQwFAQwQAgwPAQICAAJuAAAAAAwFAwwQAgwPAQICAAJcAAAAAAwFBAwQAgwPAQICAAJvAAAAAAwFBQwQAgwPAQICAAJUAAAAAAwFAwwQAgAADgUMBQEMEAIMDwECAgACagAAAAAMBQIMEAIAAA4BDAUBDBACDA8BAgIAAm4AAAAADAUDDBACDA8BAgIAAmoAAAAADAUEDBACDA8BAgIAAm8AAAAADAUFDBACDA8BAgIAAlQAAAAADAUEDBACDA8BAj4ACQAAAAwFCQwQAgwADwECAAACYAAADgUMBQMMEAIMAA8BAgAAAmEAAAAMBQUMEAIMDwECAgABBUdhdWdlDwECAAACDAAAAAwFDQwQAgwPAQICAAJkAA8BAgAAAgwAAAAMBREMEAIMAAAAAAwFFQwQAgwAAAAADAULDBACDAAPAQIAAAJgAAAADAUDDBACAAAOAwwFBwwQAhAQDA8CAlIACAJTAAUGAAAAAAAAAAAAAAAAAAAAAAAOAQwFAAwQAgAADgcMBQEMEAIAAA4GDAUBDBACDA8BAgIAAlQAAAAADAUCDBACDA8BAgIAAQVNaWRjbwAAAAwFAwwQAgwPAQICAAJxAAAAAAwFBAwQAgwPAQICAAEGJm5ic3A7AAAADAUFDBACDA8BAgIAAlQAAAAADAUGDBACDA8BAgIAAmoAAAAADAUCDBACAAAOBgwFAQwQAgwPAQICAAJUAAAAAAwFAgwQAgwPAQICAAJxAAAAAAwFAwwQAgwPAQICAAJxAAAAAAwFBAwQAgwPAQICAAJyAAAAAAwFBQwQAgwPAQICAAJcAAAAAAwFBgwQAgwPAQICAAJqAAAAAAwFAwwQAgAADgYMBQEMEAIMDwECAgACXAAAAAAMBQIMEAIMDwECAgACcQAAAAAMBQMMEAIMDwECAgACcQAAAAAMBQQMEAIMDwECAgACcgAAAAAMBQUMEAIMDwECAgACagAAAAAMBQYMEAIMDwECAgACagAAAAAMBQQMEAIAAA4GDAUBDBACDA8BAgIAAlwAAAAADAUCDBACDA8BAgIAAnEAAAAADAUDDBACDA8BAgIAAnEAAAAADAUEDBACDA8BAgIAAnIAAAAADAUFDBACDA8BAgIAAQE0AAAADAUGDBACDA8BAgIAAmoAAAAADAUFDBACAAAOBgwFAQwQAgwPAQICAAJqAAAAAAwFAgwQAgwPAQICAAJxAAAAAAwFAwwQAgwPAQICAAJxAAAAAAwFBAwQAgwPAQICAAJyAAAAAAwFBQwQAgwPAQICAAEBNQAAAAwFBgwQAgwPAQICAAJqAAAAAAwFBgwQAgAADgYMBQEMEAIMDwECAgACagAAAAAMBQIMEAIMDwECAgACcQAAAAAMBQMMEAIMDwECAgACcQAAAAAMBQQMEAIMDwECAgACcgAAAAAMBQUMEAIMDwECAgACbwAAAAAMBQYMEAIMDwECAgACagAAAAAMBQcMEAIMDwECPgAJAAAADAUJDBACDAAPAQIAAAJgAAAOEwwFAwwQAgwADwECAAACYQAAAAwFBwwQAgwAAAAADAURDBACDA8BAgIAAQ5GdWVsbGluZyBQb2ludA8BAgAAAgwAAAAMBRUMEAIMAAAAAAwFJwwQAgwPAQICAAEQRnVlbGxpbmcgQ29udHJvbA8BAgAAAgwAAAAMBT0MEAIMDwECAgABDE5venpsZSBQb2ludA8BAgAAAgwAAAAMBU0MEAIMAAAAAAwFUQwQAgwAAAAADAVXDBACDAAAAAAMBVsMEAIMAAAAAAwFYQwQAgwAAAAADAVlDBACDAAAAAAMBWsMEAIMAAAAAAwFbwwQAgwAAAAADAV1DBACDAAAAAAMBXkMEAIMAAAAAAwFfwwQAgwAAAAADAWDDBACDAAAAAAMBYUMEAIMDwECAgABDkRlY2ltYWwgUGxhY2VzDwECAAACDAAAAAwFCwwQAgwADwECAAACYAAAAAwFBAwQAgAADgMMBQcMEAIQEAwPAgJSAAgCUwAFAgAAAAAAAAAAAAAAAAAAAAAADgEMBQAMEAIAAA4DDAUBDBACAAAOAwwFAQwQAgwPAQICAAJUAAAAAAwFAgwQAgwPAQICAAJUAAAAAAwFAwwQAgwPAQICAAJUAAAAAAwFAgwQAgAADgMMBQEMEAIMDwECAgACXAAAAAAMBQIMEAIMDwECAgACVAAAAAAMBQMMEAIMDwECAgACXAAAAAAMBQMMEAIMDwECPgAJAAAADAUJDBACDAAPAQIAAAJgAAAOAwwFAwwQAgwADwECAAACYQAAAAwFBQwQAgwPAQICAAIaAA8BAgAAAgwAAAAMBQ0MEAIMDwECAgABDFByaW50ZXIgUG9ydA8BAgAAAgwAAAAMBQsMEAIMAA8BAgAAAmAAAAAMBQUMEAIAAA4DDAUHDBACEBAMDwICUgAIAlMABQEAAAAAAAAAAAAAAAAAAAAAAA4BDAUADBACAAAOAgwFAQwQAgAADgMMBQEMEAIMDwECAgACVAAAAAAMBQIMEAIMDwECAgACdAAAAAAMBQMMEAIMDwECAgACVAAAAAAMBQIMEAIMDwECPgAJAAAADAUJDBACDAAPAQIAAAJgAAAOAwwFAwwQAgwADwECAAACYQAAAAwFBQwQAgwPAQICAAI9AA8BAgAAAgwAAAAMBQ0MEAIMDwECAgABCFVQUyBQb3J0DwECAAACDAAAAAwFCwwQAgwADwECAAACYAAAAAwFBgwQAgAADgEMBQcMEAIAAA4DDAUADBACAAAOCQwFBQwQAgwMDwECUgAIAAwIEAcQBQABC1NlbGVjdCBQdW1wAQItMQkIEAUAAQgwMSBNaWRjbwJUAAkIEAUAAQgwMiBNaWRjbwJcAAkIEAUAAQgwMyBNaWRjbwJqAAkIEAUAAQgwNCBNaWRjbwJzAAkIEAUAAQgwNSBNaWRjbwJ0AAkIEAUAAQgwNiBNaWRjbwJvAAkIAAAMBQkMEAINDA8BAQdDaGVja2VkCQAAAAAADAULDBACDA8BAgIAAhgAAAAADAUXDBACDQwPAQKDAAkAAAAAAAwFGQwQAgwPAQICAAEFMDA6MDAAAAAMBR8MEAINDA8BAoMACQAAAAAADAUhDBACDQwPAQKDAAkAAAAAAAwFIwwQAg0MDwECgwAJAAAAAAAMBSUMEAINDA8BAoMACQAAAAAADAUBDBACAAAOBQwFAwwQAgwPAQICAAEKRlRQIFNlcnZlcg8BAgAAAgwAAAAMBQcMEAIMDwECAgABGGZ0cGNtc3JvLmluZGlhbm9pbC5jby5pbgAAAAwFDQwQAgwPAQICAAEMcm9hdXRvbWF0aW9uAAAADAUTDBACDA8BAgIAAocAAAAADAUZDBACDA8BAgIAAkYAAAAADAUCDBACAAAOAwwFBwwQAhAQDA8CAlIACAJTAAUBAAAAAAAAAAAAAAAAAAAAAAAOAQwFAAwQAgAADgIMBQEMEAIAAA4FDAUADBACAAAOAgwFAQwQAgwPAQI+AAkAAAAMBQMMEAIMDwECPgAJAAAADAUBDBACDA8BAgIAAnIAAAAADAUCDBACDA8BAgIAAnIAAAAADAUDDBACDA8BAgIAAnIAAAAADAUEDBACDA8BAgIAAnIAAAAADAUCDBACDA8BAj4ACQAAAAwFCQwQAgwADwECAAACYAAADgMMBQMMEAIMAA8BAgAAAmEAAAAMBQUMEAIMDwECAgABBVNoaWZ0DwECAAACDAAAAAwFEQwQAgwPAQICAAEKU2hpZnQgVGltZQ8BAgAAAgwAAAAMBQsMEAIMAA8BAgAAAmAAAAAMBVIMEAIMAA8BAgAAAQ1kaXNwbGF5Om5vbmU7AAAMBVQMEAIMAA8BAgAAAmAAAA4CDAUDDBACDAAPAQIAAAJhAAAADAUFDBACAAAOAQwFAAwQAgAADgQMBQUMEAIMDA8BAlIACAAMCBAHEAUAAnsAAnwACAgQBQACfQACVAAJCBAFAAJ+AAJcAAkIEAUAAn8AAmoACQgQBQACgAACcwAJCBAFAAKBAAJ0AAkIEAUAAoIAAm8ACQgAAAwFEQwQAgwADAkQBBAFAAELU2VsZWN0IFR5cGUCfAAICAAAAAAADAUVDBACDAAMCRABEAUAAQ1TZWxlY3QgTm96emxlAnwACAgAAAwFGQwQAgwMDwECUgAIAAwIEBIQBQABClNlbGVjdCBNT1ACfAAICBAFAAEEQ2FzaAJUAAkIEAUAAQlYdHJhUG93ZXICXAAJCBAFAAELQ3JlZGl0IENhcmQCagAJCBAFAAEGQ3JlZGl0AnMACQgQBQABB093biBVc2UCdAAJCBAFAAEIU2FtcGxpbmcCbwAJCBAFAAEKVFQgUmVjZWlwdAEBNwkIEAUAAQlSZWN5Y2xpbmcBATgJCBAFAAEKUmVkdW1wdGlvbgEBOQkIEAUAAQlMQSBDb3Vwb24BAjEwCQgQBQABCUJSIENvdXBvbgECMTEJCBAFAAEJU1IgQ291cG9uAQIxMgkIEAUAAQtDcmVkaXQgU2xpcAECMTMJCBAFAAELWHBvdyBDb3Vwb24BAjE0CQgQBQABC1hyd2QgQ291cG9uAQIxNQkIEAUAAQdNYW51YWwgAQI1MAkIEAUAAQVPdGhlcgECOTkJCAAADAVVDBACDAAPAQIAAAJgAAAADAVXDBACDAAPAQIAAAEOZGlzcGxheTogbm9uZTsAACCAAgABAAAA/////wEAAAAAAAAABAEAAAB/U3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuTGlzdGAxW1tTeXN0ZW0uU3RyaW5nLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODldXQMAAAAGX2l0ZW1zBV9zaXplCF92ZXJzaW9uBgAACAgJAgAAAAIAAAACAAAAEQIAAAAEAAAABgMAAAARY3RsMDAkYnRuX3N0b3BhbGwGBAAAABJjdGwwMCRJbWFnZUJ1dHRvbjYKCgsAAAAMEA0AEAwABQAE/////wT/////ABkaJ1N5c3RlbS5XZWIuVUkuV2ViQ29udHJvbHMuU29ydERpcmVjdGlvbk1TeXN0ZW0uV2ViLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49YjAzZjVmN2YxMWQ1MGEzYQUAHBoNU3lzdGVtLlN0cmluZ0ttc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkAEAIAAAAFAQAAEAwABQAE/////wT/////ABkbqwAFABwbrAAAEAIAAAAFAQAAABAMAAUABP////8E/////wAZG6sABQAcG6wAABADAAAAAAUBAAAQDAAFAAT/////BP////8AGRurAAUAHBusAAAQAwAAAAAFAQAAABAMAAUABP////8E/////wAZG6sABQAcG6wAAgEFRFVfTm8CLgAQBhACHhoOU3lzdGVtLkRlY2ltYWxLbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5H1QAHhuuAB9UABACHhuuAB9UAB4brgAfXAAQAh4brgAfXAAeG64AH2oAEAIeG64AH1wAHhuuAB9zABACHhuuAB9qAB4brgAfdAAQAh4brgAfagAeG64AH28AAAUBAAAQDAAFAAT/////BP////8AGRurAAUAHBusAAAQAgAAAAUBAAAQDAAFAAT/////BP////8AGRurAAUAHBusAAAQAQAABQEAABAMAAUABP////8E/////wAZG6sABQAcG6wAABABAAAFAQAAAAUAEA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/l46UC2a1oJUQc2B1u99S9gkzz3kbS1I+xPSKqwtCV"><input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value=""><input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="">
</div>



<div id="page">
<table cellpadding="0" cellspacing="0" style="width: 100%;">
<tbody><tr>
<td align="center">
  

<table cellpadding="0" cellspacing="0" width="100%">        
    <tbody><tr>
        <td style="width: 100%;" valign="top" bgcolor="#0066A1">
            <table style="width: 100%;" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td align="Center" valign="middle" style="width:180px; height:50px">
                    <img id="ctl00_Image3" src="Images/atos_logo.png" style="height:50px;width:155px;">
                </td>
                <td align="center" valign="top" style="width:200px">                                    
                    
                </td>
                <td valign="top" style="text-transform: capitalize; text-align: left; width:240px ">
                    <span id="ctl00_Label2" class="eaclabel" style="color:LightGrey;font-weight:bold;font-size:12px;text-transform: capitalize; text-align: left; padding-top: 5px;"></span>
                    <label id="Labeld" class="eaclabel" style="font-weight:bold; color:White; text-transform: capitalize; text-align: left; padding-top: 5px;">Date &amp; Time : 23-May-2015  13:42:47 </label></td>
                <td valign="top" align="right">                                
                    <img id="ctl00_Image2" src="Images/IndianOil.png">                                 
                </td>
            </tr> 
            </tbody></table>        
        </td>
    </tr>
    <tr>        
        <td bgcolor="#66A3C7">
                <table cellpadding="0" cellspacing="0" width="100%">
                    <tbody><tr>
                        <td style="width:75%; padding-left:10px" align="left" valign="middle">
                            
                            <span id="ctl00_lbl_name" class="eaclabel" style="color:White;font-weight:bold;text-transform: capitalize; text-align: left;">Mahendra Sharma Company (CODO)</span>
                            <span class="separator">|</span><span id="ctl00_lbl_sap" class="eaclabel" style="color:White;font-weight:bold;text-align: left; ">Station Code : 268532</span>                            
                            <span class="separator">|</span><span id="ctl00_Label6" class="eaclabel" style="color:White;font-weight:bold;text-align: left; ">Version : 2.0.4 (25-Feb-2015)</span>                            
                        </td>
                        <td style="height:23px; padding-right:15px" align="right">                                                            
                            <span id="ctl00_Label4" class="eaclabel" style="color:White;font-weight:bold;text-transform: capitalize; text-align: left; ">Welcome To admin </span>                                                
                            <span class="separator">|</span><a id="ctl00_LinkButton1" class="eaclabel" href='javascript:WebForm_DoPostback("ctl00$LinkButton1","",null,false,true,false,true,"")' style="color:White;font-weight:bold;text-align: left">Refresh</a>
                            <span class="separator">|</span><a id="ctl00_logout" class="eaclabel" onclick="return confirm('Are You Sure You Want To Logout?');" href='javascript:WebForm_DoPostback("ctl00$logout","",null,false,true,false,true,"")' style="color:White;font-weight:bold;text-align: left">Logout </a>
                        </td>
                    </tr>
                </tbody></table>
        </td>        
    </tr>    
    <tr>        
        <td align="left" valign="top">                
            <table cellspacing="0" cellpadding="0" width="100%">
            <tbody><tr>
                <td align="left" bgcolor="#131e3c" style="border-right:1px solid #fff; height:34px" rowspan="1">
                <span id="ctl00_Label3" style="display:inline-block;background-color:#131E3C;color:White;width:170px;font-weight: bold; text-transform: uppercase; font-family: Arial; font-size: 13px; text-align: center;">LIVE ALARMS</span></td>
                <td align="left" bgcolor="#131e3c" style="width: auto" valign="top">
                <table cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="left">
                     <ul id="css3menu1" style="width: 99%">
                        <li class="topmenu"><a id="ctl00_a1" title="Home" href="Home_Page.aspx" style="width: 70px;">HOME</a></li>
                        <li class="topmenu"><a id="ctl00_aa1" style="width: 70px;">STATUS</a>
                            <ul>
	                            <li><a id="ctl00_a2" title="Live Pump Status" href="Status_Station.aspx" style="width: 100px;">PUMP STATUS</a></li>
	                            <li><a id="ctl00_a3" title="Live Tank Status" href="Status_Tank.aspx">TANK STATUS</a></li>
	                            <li><a id="ctl00_a4" title="Device Status" href="Status_Device.aspx">DEVICE STATUS</a></li>
	                            <li><a id="ctl00_a5" title="Point of Sale(POS)" href="javascript:void(0);" onclick="PopupCenter('../Web_Page/Pump_Preset.aspx');">PUMP CONTROL</a></li>		                
                            </ul></li>
                        <li class="topmenu"><a id="ctl00_aa2" style="width: 80px;">OPERATION</a>
                            <ul>
	                            <li><a id="ctl00_a9" title="End Shift" href="Operation_Shift_ShiftEnd.aspx">END SHIFT</a></li>
	                            <li><a id="ctl00_a10" title="End Day" href="Operation_Day_DayEnd.aspx">END DAY</a></li>
	                            <li><a id="ctl00_a11" title="Mode of Payment Change" href="Operation_Transactions.aspx">MOP CHANGE</a></li>
	                            <li><a id="ctl00_a12" title="Decantation" href="Operation_Decantation.aspx">DECANTATION</a></li>
	                            <li><a id="ctl00_a13" title="Pump Auto/Manual Mode" href="Configuration_PumpMod.aspx">PUMP MODE</a></li>
	                            <li><a id="ctl00_a14" title="Fuel Product Price Change" href="Operation_PriceChange.aspx">PRICE CHANGE</a></li>
	                            <li><a id="ctl00_a15" title="Print Transaction Receipt" href="Operation_PrintTransaction.aspx">PRINT RECEIPT</a></li>			            		            		                
                            </ul></li>
                        <li class="topmenu"><a id="ctl00_aa3" style="width: 70px;">REPORTS</a>
                            <ul>
	                            <li><a id="ctl00_aa31" title="Transaction Report" style="width: 100px;">TRANSACTION</a>
	                                <ul>
	                                <li><a id="ctl00_a20" title="Fuel Transactions Report" href="Report_Sales.aspx">FUEL TRANSACTIONS</a></li>      
	                                <li><a id="ctl00_a21" title="Irregular Totalizer Report" href="Report_UncontrolledSales.aspx">IRREGULAR TOT</a></li>      
	                                <li><a id="ctl00_a22" title="Preset Qty. Mismatch With Dispensed Qty. Report" href="Report_PresetSales.aspx">PRESET MISMATCH</a></li>      
	                                <li><a id="ctl00_a23" title="Print Receipt Report" href="Report_PrintReceipt.aspx">PRINT RECEIPT</a></li>      
	                                </ul></li>	                            
	                            <li><a id="ctl00_aa32" title="Inventory(ATG)">INVENTORY</a>
	                                <ul>
		                            <li><a id="ctl00_a24" title="Current ATG Status" href="Report_Inventory_Status.aspx">CURRENT INVENTORY</a></li>
		                            <li><a id="ctl00_a25" title="Inventory Report" href="Report_Inventory.aspx">INVENTORY REPORT</a></li>
		                            <li></li>			            
		                            <li></li>			            
	                                </ul></li>			            
	                            <li><a id="ctl00_a28" title="Reconciliation Report" href="Report_Recon_OnDemand.aspx">RECONCILIATION</a></li>			            
	                            <li><a id="ctl00_a29" title="Daily Sales Report(DSR)" href="Report_DSR.aspx">DAILY SALES</a></li>
	                            <li></li>
	                            <li><a id="ctl00_aa33">SHIFT / EOD </a>
	                                <ul>
	                                <li><a id="ctl00_a31" title="Shift Report" href="Report_Shift.aspx">SHIFT REPORT</a></li>
		                            <li><a id="ctl00_a32" title="Shift Summary Report(Pump Wise)" href="Report_ShiftSummaryPump.aspx">PUMP SUMMARY</a></li>
		                            <li><a id="ctl00_a33" title="Shift Summary Report(Nozzle Wise)" href="Report_ShiftSummaryNozzle.aspx">NOZZLE SUMMARY</a></li>
		                            <li><a id="ctl00_a34" title="Shift Summary Report(Payment Wise)" href="Report_ShiftSummaryPayment.aspx">PAYMENT SUMMARY</a></li>			            
		                            <li><a id="ctl00_a35" title="CMS EOD File Report" href="Report_EODFile.aspx">CMS EOD FILE</a></li>			            
	                                </ul></li> 
                                <li><a id="ctl00_a36" title="Field Officer Inspection Report" href="Report_FieldOfficerInsp.aspx">FIELD OFFICER</a></li>
                                <li><a id="ctl00_aa34" title="Decantation">DECANTATION</a>
                                    <ul>
                                        <li><a id="ctl00_a37" title="Receipt ATG Report" href="Operation_Decantation_Report.aspx">RECEIPT ATG</a></li>
                                        <li><a id="ctl00_a38" title="TT Receipt Entry Report" href="Report_ReceiptEntry.aspx">RECEIPT ENTRY</a></li>
                                    </ul></li>	                                
	                            <li><a id="ctl00_a39" title="Transactions During Decantation" href="Report_TrxDecantation.aspx">TRX. DECANTATION</a></li>
                                <li><a id="ctl00_a40" title="Pump Wise Delivery" href="Report_PumpDelivery.aspx">PUMP DELIVERY</a></li>		                  			            	                                
	                            <li><a id="ctl00_a41" title="Operator Trail" href="Report_OperatorTrail.aspx">OPERATOR TRAIL</a></li>		                  			            
	                            <li><a id="ctl00_a42" title="Custom Report" href="Report_Custom.aspx">CUSTOM REPORT</a></li>		                  			            
	                            <li><a id="ctl00_a44" title="Audit Trails" href="Report_AuditTrail.aspx">AUDIT TRAILS</a></li>
	                            <li><a id="ctl00_a43" title="Dispenser Sales Reconciliation" href="Report_DispenserRecon.aspx">DISPENSER SALES</a></li>
                                <li><a id="ctl00_a50" title="Equipment DownTime" href="Report_Equipment_DownTime.aspx">EQUIMENT DOWNTIME</a></li>		                  			            
                            </ul></li>
                            <li class="topmenu"><a id="ctl00_aa5" style="width: 60px;">TREND</a>
                                <ul>
	                                <li><a id="ctl00_a45" title="Product Trend" href="Graph_ProductSales.aspx">PRODUCT SALES</a></li>
	                                <li><a id="ctl00_a46" title="Tank Trend" href="Graph_TankLevel.aspx">TANK WISE</a></li>
                                </ul></li>
                        <li class="topmenu"><a id="ctl00_a47" title="Event, Alarm And Device Trail Report" href="Event_Alarm_System.aspx" style="text-transform: uppercase; width: 114px;">Events &amp; Alarm</a></li>                        
                        <li class="topmenu"><a id="ctl00_aa6" title="UPS Live Status" style="text-transform: uppercase; width: 120px;">UPS Monitoring</a>
                            <ul>
	                            <li><a id="ctl00_a48" title="UPS Monitoring" href="UPS_Monitoring.aspx">UPS MONITORING</a></li>
	                            <li><a id="ctl00_a49" title="UPS Report" href="Report_UPS.aspx">UPS REPORT</a></li>
                            </ul></li>                        
                        <li style="border:none;"><a id="ctl00_aa4" style="text-transform: uppercase; width: 110px;">Configuration</a>
                            <ul>
	                            <li><a id="ctl00_a51" title="Station Configuration" href="Configuration_Config.aspx" style="width: 100px;">STATION</a></li>
	                            <li><a id="ctl00_aa41">WEB USER</a>
	                                <ul>
		                            <li><a id="ctl00_a52" title="Create New user" href="Configuration_New_User.aspx">CREATE USER</a></li>
		                            <li><a id="ctl00_a53" title="Create Role" href="Configuration_UserRole.aspx">CREATE ROLE</a></li>
		                            <li><a id="ctl00_a54" title="List of Users" href="Configuration_User_List.aspx">USERS</a></li>
		                            </ul></li>			            
	                            <li><a id="ctl00_a55" title="Transaction Print Format" href="Configuration_ReceiptFormat.aspx">PRINT FORMAT</a></li>			            		                
	                            <li><a id="ctl00_a56" title="Change Current User Password" href="Configuration_ChangePassword.aspx">CHANGE PASSWORD</a></li>			            		                
	                            <li><a id="ctl00_a57" title="System Alarm Configuration" href="Configuration_AlarmHandler.aspx">ALARM CONFIG</a></li>			            		                
                                <li><a id="ctl00_a59" title="Custom Templates Generate" href="Configuration_Custom_Report.aspx">CUSTOM TEMPLATES</a></li>			            		                
                                <li><a id="ctl00_a60" title="System Maintenance" href="Configuration_Maintenance.aspx">SYSTEM MAINTENANCE</a></li>			            		                
	                            <li><a id="ctl00_a58" title="Database Backup" href="javascript:void(0);" onclick="DownloadFiles()">DATABSE BACKUP</a></li>
	                                
                            </ul></li> 	            
                    </ul>
                    </td>
                    <td style="width:40px;padding-top:4px;" align="center" valign="middle">
                        <input type="image" name="ctl00$btn_stopall" id="ctl00_btn_stopall"  src="Images/stop_main.png" onclick="">
                    </td>
                    </tr></tbody></table>
                </td>
                
            </tr>
            <tr>
                <td style="border-right:1px solid #fff; ">                    
                </td>
                <td>
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tbody><tr>
                            <td width="40px" align="center" valign="middle">
                                <img id="ctl00_Image1" src="Images/home.png"></td>
                            <td height="23px">
                                <span id="ctl00_SiteMapPath1" class="eaclabel" style="color:#0066A1;font-weight:bold;"><a href="#ctl00_SiteMapPath1_SkipLink"><img alt="Skip Navigation Links" height="0" width="0" src="/WebResource.axd?d=8lKkG2WEPUPneqIv0IbC9PcFX9LyYfoBFyRn4zu3t%2fg%3d_IR%2b9tQ6cRPI%2fIHAxWjT%2fn2NJOLEwapyHA%2fG3K6zReaY%3d_f&amp;t=634979298260000000" style="border-width:0px;"></a><span><a title="Home Page" class="eaclabel" href="/Web_Page/Home_Page.aspx" style="color:#0066A1;text-decoration:none;">Home</a></span><span>&nbsp; &gt; &nbsp;</span><span><a class="eaclabel" style="color:#0066A1;text-decoration:none;">Configuration</a></span><span>&nbsp; &gt; &nbsp;</span><span class="eaclabel" style="color:#0066A1;text-decoration:none;">Station</span><a id="ctl00_SiteMapPath1_SkipLink"></a></span>
                                
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>    
              <tr>   
                <td align="left" rowspan="1" width="180px" valign="top" style="padding-left:5px;">                     
                    <span id="ctl00_UpdateTimer" style="display:none;visibility:hidden;"></span>
                    <div id="ctl00_UpdatePanel1">                        
                            <table cellpadding="0" cellspacing="0" width="100%" style="height:430px; border-color:White; border-style:solid; border-width:1px;">
                                <tbody><tr>
                                    <td valign="top">
                                        
	             
                                    </td>
                                </tr>
                            </tbody></table>                    
                        </div>
                </td>
                <td style="width: auto; " align="left" valign="top">                    
                    
<table style="width: 100%;" cellpadding="0" cellspacing="0">       
    <tbody><tr>
        <td style="width: 1053px">                
        <table style="width: 800px;" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td style="height: 10px">
                </td>
            </tr>
            <tr>
                <td>                    
                    <table cellpadding="0" cellspacing="0" style="width: 100%">
                        <tbody><tr>
                            <td align="right" style="width: 148px">
                            </td>
                            <td style="width:10px">
                            </td>
                            <td style="width: 221px">
                            </td>
                            <td style="width: 106px">
                            </td>
                            <td align="right">
                                    <input type="submit" name="ctl00$ContentPlaceHolder1$btn_send_config" value="Send Configuration" onclick=""></td>
                        </tr>
                    </tbody></table>                    
                </td>
            </tr>                        
            <tr>
                <td style="width: 800px; vertical-align: top; text-align: left; padding-left: 20px;">
                    <span id="ctl00_ContentPlaceHolder1_message" class="eaclabel" style="display:inline-block;color:Red;height:20px;">Note : * Fields Are Mandatory.</span>                                        
                    <table cellpadding="1" cellspacing="1" width="100%" style="border-right: black 1px solid; border-top: black 1px solid; border-left: black 1px solid; border-bottom: black 1px solid">
                    <tbody><tr>
                    <td>                    
                        <table style="width:100%; text-align: center; border-right: darkgray 2px solid; border-top: darkgray 2px solid; border-left: darkgray 2px solid; border-bottom: darkgray 2px solid;" cellpadding="0" cellspacing="0">
                        <tbody><tr>
                            <td style="width:10%">
                            <a id="ctl00_ContentPlaceHolder1_lnkTab1" class="ViewStyleActive" href='javascript:WebForm_DoPostback("ctl00$ContentPlaceHolder1$lnkTab1","",null,false,true,false,true,"")' style="width:100px;display:inline-block;">GENERAL</a></td>
                            <td style="width:10%">
                            <a id="ctl00_ContentPlaceHolder1_lnkTab2" class="ViewStyle" href='javascript:WebForm_DoPostback("ctl00$ContentPlaceHolder1$lnkTab2","",null,false,true,false,true,"")' style="width:100px;display:inline-block;">PRODUCT</a></td>
                            <td style="width:10%">
                            <a id="ctl00_ContentPlaceHolder1_lnkTab3" class="ViewStyle" href='javascript:WebForm_DoPostback("ctl00$ContentPlaceHolder1$lnkTab3","",null,false,true,false,true,"")' style="width:100px;display:inline-block;">TANK</a></td>
                            <td style="width:10%">
                            <a id="ctl00_ContentPlaceHolder1_lnkTab4" class="ViewStyle" href='javascript:WebForm_DoPostback("ctl00$ContentPlaceHolder1$lnkTab4","",null,false,true,false,true,"")' style="width:100px;display:inline-block;">DISPENSER</a></td>
                            <td style="width:10%">
                            <a id="ctl00_ContentPlaceHolder1_lnkTab5" class="ViewStyle" href='javascript:WebForm_DoPostback("ctl00$ContentPlaceHolder1$lnkTab5","",null,false,true,false,true,"")' style="width:100px;display:inline-block;">PRINTER</a></td>                            
                            <td style="width:10%">
                            <a id="ctl00_ContentPlaceHolder1_lnkTab6" class="ViewStyle" href='javascript:WebForm_DoPostback("ctl00$ContentPlaceHolder1$lnkTab6","",null,false,true,false,true,"")' style="width:100px;display:inline-block;">UPS</a></td>                            
                            <td style="width:10%">
                            <a id="ctl00_ContentPlaceHolder1_lnkTab7" class="ViewStyle" href='javascript:WebForm_DoPostback("ctl00$ContentPlaceHolder1$lnkTab7","",null,false,true,false,true,"")' style="width:100px;display:inline-block;">OPERATION</a></td>
                            <td style="width:30%"></td>
                        </tr>
                        </tbody></table> 
                    </td>
                    </tr>
                    <tr>
                    <td>
                                       
                            <table width="100%" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td style="width: 200px; height: 15px;">
                                </td>
                                <td style="width: 240px;">
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" colspan="3" style="height:30px">
                                    <span id="ctl00_ContentPlaceHolder1_Label18" class="eaclabel_c" style="display:inline-block;color:DimGray;width:80%;font-size:17pt;">General Configuration</span>                                                                                                        
                                 </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;">
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>                                       
                            <tr>
                                <td style="vertical-align: middle; text-align: center; height: 30px">
                                    <span id="ctl00_ContentPlaceHolder1_Label6" style="display:inline-block;color:#804040;width:150px;font-size:14pt;text-align: left">Location</span></td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 5px;">
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label2" class="eaclabel" style="display:inline-block;width:80px;">Country :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" value="India" maxlength="30" name="ctl00$ContentPlaceHolder1$txt_country" id="ctl00_ContentPlaceHolder1_txt_country" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator10" style="visibility:hidden;color:Red;">Only Alphabets</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label144" class="eaclabel" style="display:inline-block;width:165px;">Country of Station.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                <span id="ctl00_ContentPlaceHolder1_Label53" class="eaclabel" style="display:inline-block;width:80px;">Region :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" value="Jaipur" maxlength="30" name="ctl00$ContentPlaceHolder1$txt_region" id="ctl00_ContentPlaceHolder1_txt_region" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator11" style="visibility:hidden;color:Red;">Only Alphabets</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label145" class="eaclabel" style="display:inline-block;width:165px;">Region of Station.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label4" class="eaclabel" style="display:inline-block;width:80px;">State :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" value="Rajasthan" maxlength="30" name="ctl00$ContentPlaceHolder1$txt_state" id="ctl00_ContentPlaceHolder1_txt_state" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator12" style="visibility:hidden;color:Red;">Only Alphabets</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label5" class="eaclabel" style="display:inline-block;width:165px;">State of Station.</span></td>
                            </tr>
                            <tr>
                                <td style="height: 10px;">
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            
                            <tr>
                                <td style="vertical-align: middle; text-align: center; height: 30px">
                                    <span id="ctl00_ContentPlaceHolder1_Label54" style="display:inline-block;color:#804040;width:150px;font-size:14pt;text-align: left">Station</span></td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 5px;">
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; ">
                                    </td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    
                                    </td>
                                <td align="left">
                                    
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label14" class="eaclabel" style="display:inline-block;width:80px;">*Station :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" value="Mahendra Sharma Company" maxlength="50" name="ctl00$ContentPlaceHolder1$txt_site_name" id="ctl00_ContentPlaceHolder1_txt_site_name" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator5" style="visibility:hidden;color:Red;">Only Alphabets</span>
                                    </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label147" class="eaclabel" style="display:inline-block;width:165px;">Station Name.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label7" class="eaclabel" style="display:inline-block;width:80px;">*Type :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" value="CODO" maxlength="30" name="ctl00$ContentPlaceHolder1$txt_site_type" id="ctl00_ContentPlaceHolder1_txt_site_type" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator9" style="visibility:hidden;color:Red;">Only Alphabets</span>
                                    </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label8" class="eaclabel" style="display:inline-block;width:185px;">Type of Station. Ex. COCO</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label9" class="eaclabel" style="display:inline-block;width:80px;">Group :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" maxlength="30" name="ctl00$ContentPlaceHolder1$txt_site_group" id="ctl00_ContentPlaceHolder1_txt_site_group" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator13" style="visibility:hidden;color:Red;">Only Alphabets</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label11" class="eaclabel" style="display:inline-block;width:185px;">Group of Station.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label23" class="eaclabel" style="display:inline-block;width:80px;">DO Name :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                <input type="text" value="Jaipur" maxlength="50" name="ctl00$ContentPlaceHolder1$txt_do_nm" id="ctl00_ContentPlaceHolder1_txt_do_nm" class="eactext" style="width:180px;">
                                <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator20" style="visibility:hidden;color:Red;">Only Alphabets</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label159" class="eaclabel" style="display:inline-block;width:175px;">Divisional Officer Name of Station.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label15" class="eaclabel" style="display:inline-block;width:80px;">*Dealer :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                <input type="text" value="Mr Mahendra Sharma" maxlength="50" name="ctl00$ContentPlaceHolder1$txt_dealer_nm" id="ctl00_ContentPlaceHolder1_txt_dealer_nm" class="eactext" style="width:180px;">
                                <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator3" style="visibility:hidden;color:Red;">Only Alphabets</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label148" class="eaclabel" style="display:inline-block;width:165px;">Dealer Name of Station.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label161" class="eaclabel" style="display:inline-block;width:80px;">*Mobile No :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px; height: 30px;">
                                    <input type="text" value="+91-9414050430" maxlength="15" name="ctl00$ContentPlaceHolder1$txt_mobile_no" id="ctl00_ContentPlaceHolder1_txt_mobile_no" class="eactext" style="width:180px;">                                    
                                    </td>
                                <td align="left" style="height: 30px">
                                    <span id="ctl00_ContentPlaceHolder1_Label160" class="eaclabel" style="display:inline-block;width:264px;">Dealer Mobile No. Ex. +00-0000000000</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 10px;">
                                </td>
                                <td>                                                                        
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator2" style="visibility:hidden;color:Red;">Mobile Number is Not Matching the Format.</span>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: center; height: 30px">
                                    <span id="ctl00_ContentPlaceHolder1_Label55" style="display:inline-block;color:#804040;width:150px;font-size:14pt;text-align: left">Station Code</span></td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 5px;">
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label57" class="eaclabel" style="display:inline-block;width:80px;">*SAP Code :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" value="268532" maxlength="10" name="ctl00$ContentPlaceHolder1$txt_station_sap" id="ctl00_ContentPlaceHolder1_txt_station_sap" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator1" style="visibility:hidden;color:Red;">Only Numbers</span>
                                    </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label149" class="eaclabel" style="display:inline-block;width:190px;">SAP Code.  Ex. 000000</span>
                                </td>
                            </tr>                            
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label171" class="eaclabel" style="display:inline-block;width:80px;">DO Code :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" value="1301" maxlength="10" name="ctl00$ContentPlaceHolder1$txt_do_code" id="ctl00_ContentPlaceHolder1_txt_do_code" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator21" style="visibility:hidden;color:Red;">Only Numbers</span>
                                    </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label39" class="eaclabel" style="display:inline-block;width:190px;">Divisional Officer Code Ex. 000000</span>
                                </td>
                            </tr>                            
                            <tr>
                                <td style="height: 10px;">
                                </td>
                                <td>                                    
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: center; height: 30px">
                                    <span id="ctl00_ContentPlaceHolder1_Label56" style="display:inline-block;color:#804040;width:150px;font-size:14pt;text-align: left">Contact Detail</span></td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 5px;">
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label16" class="eaclabel" style="display:inline-block;width:80px;">*Address :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" value="RIICO SP4 Ext" maxlength="30" name="ctl00$ContentPlaceHolder1$txt_add1" id="ctl00_ContentPlaceHolder1_txt_add1" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator14" style="visibility:hidden;color:Red;">No Special Char.</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label151" class="eaclabel" style="display:inline-block;width:165px;">Station Address 1.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label17" class="eaclabel" style="display:inline-block;width:80px;">Address :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" value="Bagru " maxlength="30" name="ctl00$ContentPlaceHolder1$txt_add2" id="ctl00_ContentPlaceHolder1_txt_add2" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator15" style="visibility:hidden;color:Red;">No Special Char.</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label152" class="eaclabel" style="display:inline-block;width:165px;">Station Address 2.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                    <span id="ctl00_ContentPlaceHolder1_Label58" class="eaclabel" style="display:inline-block;width:80px;">Address :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                    <input type="text" maxlength="30" name="ctl00$ContentPlaceHolder1$txt_add3" id="ctl00_ContentPlaceHolder1_txt_add3" class="eactext" style="width:180px;">
                                    <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator16" style="visibility:hidden;color:Red;">No Special Char.</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label150" class="eaclabel" style="display:inline-block;width:165px;">Station Address 3.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                <span id="ctl00_ContentPlaceHolder1_Label19" class="eaclabel" style="display:inline-block;width:80px;">*City :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                <input type="text" value="Jaipur" maxlength="30" name="ctl00$ContentPlaceHolder1$txt_city" id="ctl00_ContentPlaceHolder1_txt_city" class="eactext" style="width:180px;">
                                <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator17" style="visibility:hidden;color:Red;">Only Alphabets</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label153" class="eaclabel" style="display:inline-block;width:165px;">Station City.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                <span id="ctl00_ContentPlaceHolder1_Label12" class="eaclabel" style="display:inline-block;width:80px;">*Pincode :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                <input type="text" value="302007" maxlength="6" name="ctl00$ContentPlaceHolder1$txt_pincode" id="ctl00_ContentPlaceHolder1_txt_pincode" class="eactext" style="width:180px;">
                                <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator6" style="visibility:hidden;color:Red;">Invalid Pincode</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label24" class="eaclabel" style="display:inline-block;width:220px;">Pincode of Station. Ex. 000000</span>
                                </td>
                            </tr>                            
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                <span id="ctl00_ContentPlaceHolder1_Label21" class="eaclabel" style="display:inline-block;width:80px;">*Contact :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                <input type="text" value="000-0000000" maxlength="11" name="ctl00$ContentPlaceHolder1$txt_contact" id="ctl00_ContentPlaceHolder1_txt_contact" class="eactext" style="width:180px;">
                                <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator8" style="visibility:hidden;color:Red;">Invalid Contact</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label154" class="eaclabel" style="display:inline-block;width:264px;">Station Phone Number. Ex. 000-0000000</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align: middle; text-align: right; height: 30px;">
                                <span id="ctl00_ContentPlaceHolder1_Label172" class="eaclabel" style="display:inline-block;width:80px;">*E-mail :</span></td>
                                <td style="vertical-align: middle; text-align: left; padding-left:8px">
                                <input type="text" value="abc@xyz.com" maxlength="50" name="ctl00$ContentPlaceHolder1$txt_site_email" id="ctl00_ContentPlaceHolder1_txt_site_email" class="eactext" style="width:180px;">
                                <span id="ctl00_ContentPlaceHolder1_RegularExpressionValidator7" style="visibility:hidden;color:Red;">Invalid Email</span>
                                </td>
                                <td align="left">
                                    <span id="ctl00_ContentPlaceHolder1_Label176" class="eaclabel" style="display:inline-block;width:264px;">Station E-mail. Ex. abc@xyz.com</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="height: 20px;">
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" colspan="3" style="height:20px">
                                 <table style="width: 70%" cellpadding="0" cellspacing="0">
                                    <tbody><tr>
                                        <td align="center" style="width: 200px;">
                                            <input type="submit" name="ctl00$ContentPlaceHolder1$site_edit" value="Save" onclick=""></td>
                                        <td align="center" style="width: 200px;">
                                            <input type="submit" name="ctl00$ContentPlaceHolder1$site_del" value="Delete" onclick=""></td>
                                        <td align="center" style="width: 200px;">
                                            <input type="submit" name="ctl00$ContentPlaceHolder1$site_clear" value="Reset" onclick=""></td>
                                    </tr> 
                                    <tr>
                                        <td align="left" colspan="3" style="height: 20px">
                                            <span id="ctl00_ContentPlaceHolder1_message_general" class="eaclabel" style="color:Red;"></span>                                            
                                        </td>
                                    </tr>
                                </tbody></table> 
                            </td>
                        </tr>
                        </tbody></table>                                                                                    
                    </td>
                    </tr>
                    </tbody></table>
                </td>
            </tr>         
            <tr>
                <td style="height: 20px;">
                </td>            
            </tr>            
        </tbody></table>                           
        </td>
    </tr>
</tbody></table> 

                </td>
              </tr>  
            </tbody></table>
        </td>
    </tr>
    <tr> 
    <td height="50px"></td>   
        
    </tr>    
</tbody></table> 
<input type="submit" name="ctl00$btnHidden" value="Download" onclick="">


<div id="ctl00_pump_Panel" class="modalBox" style="height: 360px; width: 415px; display: none; position: fixed; z-index: 100001; left: 593px; top: 422px;">
	
    <div class="popup_Titlebar" id="Div4">
        <div class="TitlebarLeft"><span id="ctl00_Label46">PUMP OPERATION CONTROL</span></div>
        <div class="TitlebarRight">
            <input type="image" name="ctl00$ImageButton6" id="ctl00_ImageButton6" title="Close" src="Images/cross_icon_normal.png" alt="Close" align="middle" onclick="">
        </div>        
    </div>
    <br>
    <div id="ctl00_UpdatePanel2">
		
    <div>
        <table cellpadding="0" cellspacing="0" style="width: 415px">
            <tbody><tr>
                <td style="width: 15px">
                </td>
                <td align="center" valign="middle">
                    <img id="ctl00_Image4" src="Images/pump.png" style="height:120px;width:130px;"></td>
                <td align="center" valign="top">
                    <table cellpadding="0" cellspacing="0" width="100%">
                        <tbody><tr>
                            <td width="35%"></td>
                            <td align="center" height="5">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span id="ctl00_Label18" class="eaclabel_r" style="display:inline-block;width:70px;">Pump</span>    
                            </td>
                            <td align="center" height="40">
                                <select name="ctl00$DropDownList3" onchange="setTimeout('__doPostBack(\'ctl00$DropDownList3\',\'\')', 0)" id="ctl00_DropDownList3" class="eactext" style="background-color:#FFC0C0;width:130px;">
			<option value="-1">Select Pump</option>
			<option value="1">01 Midco</option>
			<option value="2">02 Midco</option>
			<option value="3">03 Midco</option>
			<option value="4">04 Midco</option>
			<option value="5">05 Midco</option>
			<option value="6">06 Midco</option>

		</select>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" colspan="2">
                                <table cellpadding="0" cellspacing="0" width="85%" style="border:1px solid #000;" height="70px">
                                    <tbody><tr>
                                        <td align="center">                            
                                            <input type="submit" name="ctl00$btn_autho" value="Authorize" onclick="">
                                        </td>
                                        <td align="center">
                                            <input type="submit" name="ctl00$btn_deautho" value="Deauthorize" onclick="">
                                        </td>                                        
                                   </tr>
                                    <tr>
                                        <td align="center">
                                            <input type="submit" name="ctl00$btn_start" value="Start" onclick="">                                            
                                        </td>
                                        <td align="center">
                                            <input type="submit" name="ctl00$btn_stop" value="Stop" onclick="">                                            
                                        </td>                                        
                                    </tr>
                                </tbody></table>                                                                
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span id="ctl00_Label7" class="eaclabel_r" style="display:inline-block;width:75px;">Sale Type</span>
                            </td>
                            <td align="center" height="35">
                                <select name="ctl00$DropDownList1" onchange="setTimeout('__doPostBack(\'ctl00$DropDownList1\',\'\')', 0)" id="ctl00_DropDownList1" tabindex="1" class="eactext" style="background-color:#FFC0C0;width:130px;">
			<option value="-1">Select Type</option>
			<option value="1">Volume</option>
			<option value="2">Amount</option>
			<option value="0">Top UP</option>

		</select>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span id="ctl00_Label8" class="eaclabel_r" style="display:inline-block;width:75px;">Pump Nozzle</span>
                            </td>
                            <td align="center" height="35">
                                <select name="ctl00$DropDownList2" id="ctl00_DropDownList2" tabindex="2" class="eactext" style="background-color:#FFC0C0;width:130px;">
			<option value="-1">Select Nozzle</option>

		</select>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span id="ctl00_Label9" class="eaclabel_r" style="display:inline-block;width:75px;">MOP Type</span>
                            </td>
                            <td align="center" height="35">
                                <select name="ctl00$DropDownList4" id="ctl00_DropDownList4" tabindex="2" class="eactext" style="background-color:#FFC0C0;width:130px;">
			<option value="-1">Select MOP</option>
			<option value="1">Cash</option>
			<option value="2">XtraPower</option>
			<option value="3">Credit Card</option>
			<option value="4">Credit</option>
			<option value="5">Own Use</option>
			<option value="6">Sampling</option>
			<option value="7">TT Receipt</option>
			<option value="8">Recycling</option>
			<option value="9">Redumption</option>
			<option value="10">LA Coupon</option>
			<option value="11">BR Coupon</option>
			<option value="12">SR Coupon</option>
			<option value="13">Credit Slip</option>
			<option value="14">Xpow Coupon</option>
			<option value="15">Xrwd Coupon</option>
			<option value="50">Manual </option>
			<option value="99">Other</option>

		</select>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" height="40" colspan="2" valign="middle">
                                <table cellpadding="0" cellspacing="0">
                                    <tbody><tr>
                                        <td width="110px">
                                            <input type="text" value="0.00" name="ctl00$txt_data" id="ctl00_txt_data" tabindex="3" class="eactext" style="border-color:Black;border-width:1px;border-style:Solid;width:98px;font-weight:bold;">
                                        </td>
                                        <td width="22px">
                                            <span id="ctl00_lbl_vm" class="eaclabel_c">Ltr.</span>
                                        </td>
                                    </tr>
                                </tbody></table>                                
                            </td>
                        </tr>
                        <tr>                        
                            <td align="center" valign="top" colspan="2">
                            <table cellpadding="0" cellspacing="0" width="90%">
                                    <tbody><tr>
                                        <td align="center">                            
                                            <input type="submit" name="ctl00$btn_set" value="Preset" onclick="">
                                        </td>
                                        <td align="center">
                                            <input type="submit" name="ctl00$btn_reset" value="Reset" onclick="">
                                        </td>
                                   </tr>
                          </tbody></table>
                        </td></tr>
                    </tbody></table>
                </td>
            </tr>
            <tr>
                <td style="width: 15px">
                </td>
                <td colspan="2" height="20">
                    <span id="ctl00_message_log" class="eaclabel" style="color:Red;"></span>
                </td>
            </tr>
            <tr>
                <td style="width: 15px">
                </td>
                <td style="width: 145px">
                </td>
                <td>
                </td>
            </tr>
        </tbody></table>
    </div>
    
	</div>

</div>
<input type="submit" name="ctl00$Button28" value="" onclick="">


<div id="mpe_backgroundElement" class="modalBackground" style="display: none; position: fixed; left: 0px; top: 0px; z-index: 10000; width: 1186px; height: 1208px;"></div></td>
</tr>
<tr>
    <td>
        <div style="margin:0px; padding: 0px 0px 0px 150px; bottom:0px; height:23px; float:left; position:fixed; width:100%; background-color: #131e3c;">
         </div></td></tr></tbody></table></div>
            <input type="submit" name="ctl00$DoNothing" value="" onclick="">



</form>
</body>
</html>